### ISSUE TITLE
Tagged Version

### ISSUE THREAD

**Issue by hairmare** [jedisct1/siphash-php#1]
Thanks for implementing the SipHash functions for PHP.

I'd like to package the extension for some distros to help deploy it. For this a tagged version of the extension would be very handy.

Can I ask you to tag the current master with a proper x.y.z tag? This would make packaging the extension much easier on my side.

Thanks for your consideration and thanks again for all the work you put into the extension.

**Comment by jedisct1** [comment]
This extension was useful a while back, but I don't think it is the case any more.

siphash is part of libsodium, also of the libsodium PHP extension, which will also be bundled with PHP 7.2

**Comment by hairmare** [comment]
Thanks for the info. Given that I need a siphash solution soonish I'll probably refactor my code to use [sodium_compat](https://github.com/paragonie/sodium_compat) while I wait for php 7.2. 

I don't expect 7.2 to land in Debian proper for some time given that Debian 9 (which I am targeting) recently shipped 7.0.

**Update:** Even better, Debian already ships php-libsodium 🎉

**Comment by jedisct1** [comment]
I still added a 0.1.0 tag to the current repos.

**Comment by hairmare** [comment]
Cool, thanks anyway :)
