### ISSUE TITLE
PHP 8.1 Support?

### ISSUE THREAD

**Issue by pnill** [jedisct1/siphash-php#2]
This doesn't currently compile for PHP 8.1, 

Seems  `TSRMLS_CC` was deprecated, and removing it throws:
`PHP Warning:  Missing arginfo for sip_hash() in Unknown on line 0`

I would guess relating to `ZEND_BEGIN_ARG_INFO_EX` missing, and it wanting it not entirely sure, going to continue working towards it and will follow up if I figure it out for others to use.

**Comment by jedisct1** [comment]
SipHash is already included by default in PHP 8: https://www.php.net/manual/en/function.sodium-crypto-shorthash.php

**Comment by pnill** [comment]
> SipHash is already included by default in PHP 8: https://www.php.net/manual/en/function.sodium-crypto-shorthash.php

Sorry not to bump a closed issue, but the reasoning for using this over the included algorithm was the target on the other end required changes to the algorithm I'd made to this library to support it properly as they didn't implement siphash as is and made changes. 

It does work with the TSRMLS_CC removed and just throws a warning if anyone else does end up needing to use it over the included/built-in one where you don't have control over the algorithm.
